# Generated by Django 2.0 on 2018-12-10 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('entidadId', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('saldo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('euros', models.FloatField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('sucursalId', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=9)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Banco')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=80)),
                ('bancos', models.ManyToManyField(to='principal.Banco')),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='usuarios',
            field=models.ManyToManyField(to='principal.Usuario'),
        ),
    ]
